import { describe, expect, it } from 'vitest';
import type { Coluna, ModeloLogico, Tabela } from '../../src/dtos/modelagem.schema';
import { gerarSql, renderizarTipo } from '../../src/utils/modelagem/gerarSql';

// Mesmos casos de ide-web-front/tests/features/exercicio/modelagem/gerarSql.test.ts — mantenha os dois iguais.

function col(id: string, nome: string, mudancas: Partial<Coluna> = {}): Coluna {
  return {
    id,
    nome,
    tipo: 'INTEGER',
    tamanho: null,
    escala: null,
    pk: false,
    notNull: false,
    unique: false,
    autoIncremento: false,
    padrao: '',
    check: '',
    fk: null,
    ...mudancas,
  };
}

function tabela(id: string, nome: string, colunas: Coluna[]): Tabela {
  return { id, posicao: { x: 0, y: 0 }, nome, colunas };
}

function logico(...tabelas: Tabela[]): ModeloLogico {
  return { tabelas, notas: [] };
}

describe('gerarSql', () => {
  it('modelo vazio gera SQL vazio e sem avisos', () => {
    expect(gerarSql(logico())).toEqual({ sql: '', avisos: [], tabelas: [] });
  });

  it('renderiza tipos, restrições de coluna e chave primária', () => {
    const resultado = gerarSql(
      logico(
        tabela('t1', 'Cliente', [
          col('c1', 'id', { pk: true, notNull: true, autoIncremento: true }),
          col('c2', 'Nome', { tipo: 'VARCHAR', tamanho: 100, notNull: true }),
          col('c3', 'email', { tipo: 'VARCHAR', unique: true }),
          col('c4', 'idade', { padrao: '0', check: 'idade >= 0' }),
          col('c5', 'saldo', { tipo: 'NUMERIC', tamanho: 12, escala: 2 }),
        ]),
      ),
    );

    expect(resultado.sql).toBe(
      [
        'CREATE TABLE cliente (',
        '  id INTEGER GENERATED BY DEFAULT AS IDENTITY,',
        '  nome VARCHAR(100) NOT NULL,',
        '  email VARCHAR(255) UNIQUE,',
        '  idade INTEGER DEFAULT 0 CHECK (idade >= 0),',
        '  saldo NUMERIC(12, 2),',
        '  PRIMARY KEY (id)',
        ');',
      ].join('\n'),
    );
    expect(resultado.avisos).toEqual([]);
    expect(resultado.tabelas).toEqual([
      {
        id: 't1',
        nome: 'cliente',
        colunas: [
          { id: 'c1', nome: 'id' },
          { id: 'c2', nome: 'nome' },
          { id: 'c3', nome: 'email' },
          { id: 'c4', nome: 'idade' },
          { id: 'c5', nome: 'saldo' },
        ],
        linhaInicio: 1,
        linhaFim: 8,
      },
    ]);
  });

  it('renderizarTipo usa tamanhos padrão quando não informados', () => {
    const base = { tamanho: null, escala: null };
    expect(renderizarTipo({ tipo: 'VARCHAR', ...base })).toBe('VARCHAR(255)');
    expect(renderizarTipo({ tipo: 'CHAR', ...base })).toBe('CHAR(1)');
    expect(renderizarTipo({ tipo: 'CHAR', tamanho: 2, escala: null })).toBe('CHAR(2)');
    expect(renderizarTipo({ tipo: 'NUMERIC', ...base })).toBe('NUMERIC(10, 2)');
    expect(renderizarTipo({ tipo: 'NUMERIC', tamanho: 8, escala: null })).toBe('NUMERIC(8)');
    expect(renderizarTipo({ tipo: 'TIMESTAMP', ...base })).toBe('TIMESTAMP');
  });

  it('cria a tabela referenciada antes da que tem a chave estrangeira', () => {
    const resultado = gerarSql(
      logico(
        tabela('tp', 'pedido', [
          col('p1', 'id', { pk: true, notNull: true }),
          col('p2', 'cliente_id', { notNull: true, fk: { tabelaId: 'tc', colunaId: 'c1' } }),
        ]),
        tabela('tc', 'cliente', [col('c1', 'id', { pk: true, notNull: true })]),
      ),
    );

    expect(resultado.sql).toBe(
      [
        'CREATE TABLE cliente (',
        '  id INTEGER,',
        '  PRIMARY KEY (id)',
        ');',
        '',
        'CREATE TABLE pedido (',
        '  id INTEGER,',
        '  cliente_id INTEGER NOT NULL,',
        '  PRIMARY KEY (id),',
        '  CONSTRAINT fk_pedido_cliente_id FOREIGN KEY (cliente_id) REFERENCES cliente (id)',
        ');',
      ].join('\n'),
    );
    expect(resultado.tabelas.map((t) => [t.nome, t.linhaInicio, t.linhaFim])).toEqual([
      ['cliente', 1, 4],
      ['pedido', 6, 11],
    ]);
    expect(resultado.avisos).toEqual([]);
  });

  it('agrupa FK para PK composta numa constraint e separa duas FKs para a mesma PK', () => {
    const resultado = gerarSql(
      logico(
        tabela('ta', 'aeroporto', [col('a1', 'id', { pk: true })]),
        tabela('tm', 'matricula', [col('m1', 'aluno_id', { pk: true }), col('m2', 'disciplina_id', { pk: true })]),
        tabela('tv', 'voo', [
          col('v1', 'origem_id', { fk: { tabelaId: 'ta', colunaId: 'a1' } }),
          col('v2', 'destino_id', { fk: { tabelaId: 'ta', colunaId: 'a1' } }),
        ]),
        tabela('tn', 'nota', [
          col('n1', 'id', { pk: true }),
          col('n2', 'matricula_aluno_id', { fk: { tabelaId: 'tm', colunaId: 'm1' } }),
          col('n3', 'matricula_disciplina_id', { fk: { tabelaId: 'tm', colunaId: 'm2' } }),
        ]),
      ),
    );

    expect(resultado.sql).toContain('  PRIMARY KEY (aluno_id, disciplina_id)');
    expect(resultado.sql).toContain('  CONSTRAINT fk_voo_origem_id FOREIGN KEY (origem_id) REFERENCES aeroporto (id)');
    expect(resultado.sql).toContain(
      '  CONSTRAINT fk_voo_destino_id FOREIGN KEY (destino_id) REFERENCES aeroporto (id)',
    );
    expect(resultado.sql).toContain(
      '  CONSTRAINT fk_nota_matricula_aluno_id FOREIGN KEY (matricula_aluno_id, matricula_disciplina_id) ' +
        'REFERENCES matricula (aluno_id, disciplina_id)',
    );
    expect(resultado.avisos).toEqual(['A tabela "voo" não tem chave primária.']);
  });

  it('mantém auto-referência dentro do CREATE TABLE', () => {
    const resultado = gerarSql(
      logico(
        tabela('tf', 'funcionario', [
          col('f1', 'id', { pk: true }),
          col('f2', 'gerente_id', { fk: { tabelaId: 'tf', colunaId: 'f1' } }),
        ]),
      ),
    );

    expect(resultado.sql).toContain(
      'CONSTRAINT fk_funcionario_gerente_id FOREIGN KEY (gerente_id) REFERENCES funcionario (id)',
    );
    expect(resultado.sql).not.toContain('ALTER TABLE');
  });

  it('usa ALTER TABLE no fim quando há referência circular', () => {
    const resultado = gerarSql(
      logico(
        tabela('td', 'departamento', [
          col('d1', 'id', { pk: true }),
          col('d2', 'chefe_id', { fk: { tabelaId: 'te', colunaId: 'e1' } }),
        ]),
        tabela('te', 'empregado', [
          col('e1', 'id', { pk: true }),
          col('e2', 'departamento_id', { fk: { tabelaId: 'td', colunaId: 'd1' } }),
        ]),
      ),
    );

    const linhas = resultado.sql.split('\n');
    expect(linhas.at(-1)).toBe(
      'ALTER TABLE departamento ADD CONSTRAINT fk_departamento_chefe_id FOREIGN KEY (chefe_id) REFERENCES empregado (id);',
    );
    expect(resultado.sql).toContain(
      '  CONSTRAINT fk_empregado_departamento_id FOREIGN KEY (departamento_id) REFERENCES departamento (id)',
    );
    expect(resultado.sql.indexOf('CREATE TABLE departamento')).toBeLessThan(
      resultado.sql.indexOf('CREATE TABLE empregado'),
    );
  });

  it('coloca palavra reservada entre aspas e avisa uma vez', () => {
    const resultado = gerarSql(
      logico(tabela('tu', 'User', [col('u1', 'id', { pk: true }), col('u2', 'order', { tipo: 'TEXT' })])),
    );

    expect(resultado.sql).toContain('CREATE TABLE "user" (');
    expect(resultado.sql).toContain('  "order" TEXT,');
    expect(resultado.avisos).toEqual([
      '"user" é palavra reservada do PostgreSQL; foi escrita entre aspas.',
      '"order" é palavra reservada do PostgreSQL; foi escrita entre aspas.',
    ]);
    expect(resultado.tabelas[0]?.nome).toBe('user');
  });

  it('avisa sobre nomes vazios, duplicados, tabela sem colunas e restrições inválidas', () => {
    const resultado = gerarSql(
      logico(
        tabela('t1', '', [col('c1', 'id', { pk: true })]),
        tabela('t2', 'produto', [
          col('c2', 'id', { pk: true }),
          col('c3', 'ID'),
          col('c4', ''),
          col('c5', 'codigo', { tipo: 'VARCHAR', autoIncremento: true }),
          col('c6', 'estoque', { autoIncremento: true, padrao: '1' }),
          col('c7', 'preco', { check: '(preco > 0' }),
          col('c8', 'obs', { padrao: "'x'; DROP TABLE produto" }),
        ]),
        tabela('t3', 'produto', []),
      ),
    );

    expect(resultado.avisos).toEqual([
      'Uma tabela está sem nome.',
      'A tabela "produto" tem duas colunas "id".',
      'A tabela "produto" tem uma coluna sem nome.',
      'Existem duas tabelas com o nome "produto".',
      'A tabela "produto" não tem colunas.',
      '"produto.codigo": autoincremento só vale para tipos inteiros.',
      '"produto.estoque": coluna com autoincremento não deve ter valor padrão.',
      '"produto.preco": o CHECK tem parênteses desbalanceados.',
      '"produto.obs": o valor padrão não deve conter ";".',
    ]);
    expect(resultado.sql).toContain('CREATE TABLE tabela_sem_nome_1 (');
    expect(resultado.sql).toContain('CREATE TABLE produto (\n);');
  });

  it('avisa quando a FK tem tipo diferente ou não referencia PK/UNIQUE', () => {
    const resultado = gerarSql(
      logico(
        tabela('tc', 'categoria', [col('c1', 'id', { pk: true }), col('c2', 'sigla', { tipo: 'CHAR', tamanho: 3 })]),
        tabela('tp', 'produto', [
          col('p1', 'id', { pk: true }),
          col('p2', 'categoria_id', { tipo: 'BIGINT', fk: { tabelaId: 'tc', colunaId: 'c1' } }),
          col('p3', 'categoria_sigla', { tipo: 'CHAR', tamanho: 3, fk: { tabelaId: 'tc', colunaId: 'c2' } }),
        ]),
      ),
    );

    expect(resultado.avisos).toEqual([
      '"produto.categoria_id" (BIGINT) referencia "categoria.id" (INTEGER), de outro tipo.',
      'A chave estrangeira de "produto" para "categoria" precisa referenciar a chave primária inteira ou uma coluna UNIQUE.',
    ]);
  });
});
